services:

  frontend:
    volumes:
      - ../../:/project:cached
    build: 
      context: ../..
      dockerfile: .devcontainer/docker/frontend.dockerfile
    ports:
      - 9080:8080
    command: [ "sh", "-c", "cd /project/src_frontend && flutter run -d web-server --web-port=8080 --web-hostname=0.0.0.0" ]

  backend:
    volumes:
      - ../../:/project:cached
    build:
      context: ../..
      dockerfile: .devcontainer/docker/backend.dockerfile
    ports:
      - 9081:8081
    command: [ "sh", "-c", "cd /project/src_backend && mvn spring-boot:run" ]